/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.VitalSignHistory;
import model.VitalSigns;

/**
 *
 * @author hriti
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    VitalSignHistory history;
    public ViewJPanel(VitalSignHistory history) {
        initComponents();
        
        this.history = history;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Vitals = new javax.swing.JTable();
        btn_ViewVitals = new javax.swing.JButton();
        btn_DeleteVitals = new javax.swing.JButton();
        lbl_ViewTemprature = new javax.swing.JLabel();
        lbl_ViewBloodPressure = new javax.swing.JLabel();
        lbl_ViewPulse = new javax.swing.JLabel();
        lbl_ViewDate = new javax.swing.JLabel();
        txt_ViewTemprature = new javax.swing.JTextField();
        txt_ViewbloodPressure = new javax.swing.JTextField();
        txt_ViewPulse = new javax.swing.JTextField();
        txt_ViewDate = new javax.swing.JTextField();

        lbl_Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Title.setText("View Vitals");

        tbl_Vitals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "Temprature", "Pulse"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_Vitals);

        btn_ViewVitals.setText("View");
        btn_ViewVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ViewVitalsActionPerformed(evt);
            }
        });

        btn_DeleteVitals.setText("Delete");
        btn_DeleteVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteVitalsActionPerformed(evt);
            }
        });

        lbl_ViewTemprature.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_ViewTemprature.setText("Temprature:");

        lbl_ViewBloodPressure.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_ViewBloodPressure.setText("Blood Pressure:");

        lbl_ViewPulse.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_ViewPulse.setText("Pulse:");

        lbl_ViewDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_ViewDate.setText("Date:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_ViewVitals)
                        .addGap(18, 18, 18)
                        .addComponent(btn_DeleteVitals)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_ViewBloodPressure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ViewTemprature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ViewPulse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ViewDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_ViewTemprature)
                    .addComponent(txt_ViewbloodPressure, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(txt_ViewPulse)
                    .addComponent(txt_ViewDate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lbl_Title)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ViewVitals)
                    .addComponent(btn_DeleteVitals))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ViewTemprature)
                    .addComponent(txt_ViewTemprature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ViewBloodPressure)
                    .addComponent(txt_ViewbloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ViewPulse)
                    .addComponent(txt_ViewPulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ViewDate)
                    .addComponent(txt_ViewDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DeleteVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteVitalsActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tbl_Vitals.getSelectedRow();
        
        if(selectedRowIndex < 0){
            
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel)tbl_Vitals.getModel();
        VitalSigns selectedVitals = (VitalSigns) model.getValueAt(selectedRowIndex, 0);
        
        history.deleteVitals(selectedVitals);
        
        JOptionPane.showMessageDialog(this, "Vitals Deleted");
        
        populateTable();
        
    }//GEN-LAST:event_btn_DeleteVitalsActionPerformed

    private void btn_ViewVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ViewVitalsActionPerformed
        // TODO add your handling code here:
         int selectedRowIndex = tbl_Vitals.getSelectedRow();
        
        if(selectedRowIndex < 0){
            
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel)tbl_Vitals.getModel();
        VitalSigns selectedVitals = (VitalSigns) model.getValueAt(selectedRowIndex, 0);
        
        txt_ViewTemprature.setText(String.valueOf(selectedVitals.getTemprature()));
        txt_ViewbloodPressure.setText(String.valueOf(selectedVitals.getBloodPressure()));
        txt_ViewPulse.setText(String.valueOf(selectedVitals.getPulse()));
        txt_ViewDate.setText(selectedVitals.getDate());
        
    }//GEN-LAST:event_btn_ViewVitalsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DeleteVitals;
    private javax.swing.JButton btn_ViewVitals;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JLabel lbl_ViewBloodPressure;
    private javax.swing.JLabel lbl_ViewDate;
    private javax.swing.JLabel lbl_ViewPulse;
    private javax.swing.JLabel lbl_ViewTemprature;
    private javax.swing.JTable tbl_Vitals;
    private javax.swing.JTextField txt_ViewDate;
    private javax.swing.JTextField txt_ViewPulse;
    private javax.swing.JTextField txt_ViewTemprature;
    private javax.swing.JTextField txt_ViewbloodPressure;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel)tbl_Vitals.getModel();
        model.setRowCount(0);
        for(VitalSigns vs : history.getHistory()){
        
        
            Object[] row = new Object[3];
            row[0] = vs;
            row[1] = vs.getTemprature();
            row[2] = vs.getPulse();
            
            model.addRow(row);
        
        }
        
        
        
        
       
    }
}
